name: Automated UI Playwright Tests
on: [ push ]
env:
    youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
    gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - name: cache dependencies
              uses: actions/cache@v4
              with:
                path: |
                  frontend/node-modules
                  backend/node-modules
                  test-suite/node-modules
                key: ${{ runner.os }}--node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                    ${{ runner.os }}-npm
            - name: Install dependencies for front end and run server
              working-directory: ./frontend
              run: |
                npm ci
                npm run dev &
            - name: Navigate to backend folder and download dependencies and run Hono backend
              working-directory: ./backend
              run: |
                touch .env
                echo YOUTUBE_API_KEY="$youtube_api_key" >> .env
                echo GEMINI_API_KEY="$gemini_api_key" >> .env
                npm ci
                npm run dev &
            - name: Install dependencies, Playwright browsers and run tests
              working-directory: ./test-suite
              run: |
                npm ci
                npx playwright install --with-deps
                npx playwright test
            - name: Upload Playwright Test Report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30