name: Automated UI Playwright Tests
on: [ push ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Setup node environment
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
            - name: Check for cached dependencies
              uses: actions/cache@v3
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            - name: Install dependencies and run server
              run: |
                npm ci
                npm run dev &
            - name: Navigate to backend folder and download dependencies and run Hono backend
              working-directory: ./backend
              run: |
                npm ci
                npm run dev &
            - name: Install Playwright package-lock.json and run tests
              working-directory: ./test-suite
              run: npm ci
            - name: Install Playwright Browsers
              working-directory: ./backend
              run: |
                npx playwright install --with-deps
                npx playwright test
            - name: Upload Playwright Test Report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                name: playwright-report
                path: playwright-report/
                retention-days: 30